### ISSUE TITLE
Cannot Compile Correctly?

### ISSUE THREAD

**Issue by Quorafind** [roovo/obsidian-card-board#1]
![image](https://user-images.githubusercontent.com/13215013/139399597-55bf05a1-ca03-4d24-b0ba-77918fb509cc.png)

I would love to test it for you. But it seems something haven't been finished?

**Comment by roovo** [comment]
Hi

I think you might find that you need to run

```
npm run generate
```

before trying to run/build the thing.  I will update the readme.

You may want to pull the recent changes as well, as I have fixed some bits and bobs today :)

Thanks and hope this works for you

**Comment by roovo** [comment]
apologies if I closed this before hearing back... didn't realise that if I pushed a commit referencing the issue it would auto-close it.  Please feel free to reopen if it is still an issue.

**Comment by roovo** [comment]
I've also made a [pre-release - v0.0.0-alpha](https://github.com/roovo/obsidian-card-board/releases/tag/0.1.0-beta) which should you having to build from scratch:
