### ISSUE TITLE
Custom names for "Undated" and other pre-named columns

### ISSUE THREAD

**Issue by roovo** [roovo/obsidian-card-board#105]
### Discussed in https://github.com/roovo/obsidian-card-board/discussions/102

<div type='discussions-op-text'>

<sup>Originally posted by **ItsFullOfCode** November  9, 2022</sup>
- Allow to give the “Undated” column a custom name
  - example use case: users who consider every undated task a Backlog item would be able to name the “Undated” column accordingly to "Backlog"
</div>

Allowing users to select the name for any of the automatically named columns on the boards will be nicer for non-english speaking people as they will be able to customise to their own language.

This will be high-ish on my todo list :)

**Comment by juestchaos** [comment]
+1 for this. 
Maybe in terms of time dimension, I hope to increase the corresponding column, such as the current week, the current month, and the current quarter.

**Comment by roovo** [comment]
Closing this as column names can be customized in the latest release (0.6.7).

@juestchaos -> I have tagged #93 with your comment as that issue fits better with what you are after I think :)

**Comment by juestchaos** [comment]
Thanks for your mention.
