### ISSUE TITLE
Optionally don't include tasks in Daily Notes in "Today" column

### ISSUE THREAD

**Issue by roovo** [roovo/obsidian-card-board#106]
### Discussed in https://github.com/roovo/obsidian-card-board/discussions/103

<div type='discussions-op-text'>

<sup>Originally posted by **ItsFullOfCode** November  9, 2022</sup>
- For tasks in Daily Notes: allow an option in Settings to **not** use the date of the Daily Note as the Due Date of the Task.
  - Use case: This feature would ally tasks in daily notes without an explicit due date to be shown in the "Undated" column. This would keep the "Today" column reserved for items who have an explicit due date for today or the past.</div>

Needed for drag and drop too as will need to be able to support dragging a card from a dated column to the undated column on date based boards!

**Comment by roovo** [comment]
I am thinking of using something like @due(none) to cancel the due date of a task in a daily note.  Also, will think about adding a settings option to allow (either per board or globally) the dates from daily notes to be ignored (see [discussion with @Lunairee on discord](https://discord.com/channels/686053708261228577/965681451297304596/1051840287506448494)).  Keen on keeping the number of settings as small as possible tho!

**Comment by jtarthur5** [comment]
@roovo, how high a priority is this one? Cardboard looks awesome and really fits how I want to display and use tasks. However, I do put a lot of ad-hoc tasks in my daily note which have no scheduled date, and they're currently filling my "today" column.

**Comment by roovo** [comment]
Hi @jtarthur5, it is "reasonably" high priority.  I can't give any timescales, but I would like to think it would be within the next month or so.  It really depends on how much time I find to work on things and if anything higher priority comes in (like bugs etc) :)

If you keep an eye on the [project board](https://github.com/users/roovo/projects/4) you should see the things before it getting done as I work on them.  At the moment this card is the third from the top in the "Ready to work on column"...

**Comment by roovo** [comment]
been messing with ideas in my head on this as about to start on it.... proposing to:

- add an option to global settings to not use daily note file names when setting the due date for tasks.  I was initially thinking of doing this on a per-board basis, but that could lead to cards appearing on different boards with different due dates which doesn't feel desirable.
- allow @due(none) to be placed on a task line to nullify the due date derived from the file name.  This is needed for drag and drop so that a task in a daily note can be moved to the undated column.

**Comment by roovo** [comment]
just released v0.7.2 which has this added - there's a new setting in Global Settings and `@due(none)` is supported too.  If you find any issues with it, just let me know :)
