### ISSUE TITLE
tags with emojis are ignored on a tag board

### ISSUE THREAD

**Issue by thecheesemo** [roovo/obsidian-card-board#107]
I have the following status tags:

#Status/⭕Open
#Status/🧊OnHold
#Status/🔥Active
#Status/❌Abandoned
#Status/♻Ongoing

They render properly as column headers, however, any task with those tags are treated as "other".

I tried setting everything up the exactly same, except I used:

#Status/Active
#Status/Abandoned

and it worked as intended.

**Comment by roovo** [comment]
Thanks - this actually fits in with what I will be starting on shortly so I hope to have this fixed in not too long :)

**Comment by roovo** [comment]
Hiya - just released a new version ([0.6.5](https://github.com/roovo/obsidian-card-board/releases/tag/0.6.5)) which allows any unicode in tags (as per obsidian itself), so this should be fixed for you.

Any further probs, do just let me know.  Thanks again for raising :)
