### ISSUE TITLE
Respect Editor Font

### ISSUE THREAD

**Issue by amzon-ex** [roovo/obsidian-card-board#118]
The tasks show in the Cardboard do not respect the font set for the Editor. Is it possible to automatically do this?

**Cardboard**:
![image](https://user-images.githubusercontent.com/45428344/205335024-217973da-e3c7-44a8-bd9d-b2e58637c14d.png)

**In the file**:
![image](https://user-images.githubusercontent.com/45428344/205335321-088c7060-31f4-462d-bb32-7affd703f6db.png)

**Comment by roovo** [comment]
Hiya - and sorry to have left this so long without replying!  I don't do anything to set a particular font size, I only set things like size and font-weightm, so I am not sure how/why this is happening.

All I can think of is that is is perhaps some strange interaction with either a theme, another plugin, or a css snippet you have set up.

If you could find a minimal set up in terms of plugins and theme that this happens with I can see if I can reproduce so I can see what is going on.

Many thanks and appologies again

**Comment by ltroj** [comment]
@roovo 
I could reproduce this issue.

Steps:
- Create Sandbox vault
- Install obisidan-card-board
- Set Settings/Appearance/Font/Interface font to Comic Sans, Text font to Roboto
- Switch to CardBoard: it uses Comic Sans but imo should use Roboto

![2023-02-13 09_40_22-Start Here - Obsidian Sandbox - Obsidian v1 1 9](https://user-images.githubusercontent.com/25671166/218410369-a6bbffcf-1712-431b-827d-6d1c592433c5.png)

**Comment by roovo** [comment]
Fab - thank you.  I will investigate!

**Comment by Ace131313** [comment]
Hi,
Cardboard looks a really neat app but I have the same font problem.  Firstly, Control with the scroll wheel doesn't seem to work on the Cardboard page but it does on everything else in Obsidian. Secondly, even with all other community plugins disabled and all CSS snippets disabled it still doesn't change font size with control\scroll wheel. 

I've changed the font size in the Tasks plugin but this does not affect the Cardboard page. If you need any more info let me know.

**Comment by roovo** [comment]
Hopefully the latest release (0.7.6) fixes this.  The contents of cards use the Obsidian _Text Font_ and the rest of the CardBoard interface follows the _Interface Font_ - which seems to be in keeping with how the rest of Obsidian deals with this.  I also use the font size from Obsidian settings too.

The only thing that doesn't work is use of the scroll wheel for changing the size when the mouse is over the plugin wihndow, which I haven't implemented as I am not at all sure how I could do this.
