### ISSUE TITLE
[Bug] npm install Fails with Dependency Error

### ISSUE THREAD

**Issue by darthmachina** [roovo/obsidian-card-board#12]
I thought I would check out the code to see if there are some small things I could do myself and submit PRs for since I love the start of this so far, but I'm running into the following error when running `npm install`:

```npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cardboard@0.0.1
npm ERR! Found: elm-webpack-loader@8.0.0
npm ERR! node_modules/elm-webpack-loader
npm ERR!   dev elm-webpack-loader@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer elm-webpack-loader@"^7.0.1" from elm-hot-webpack-loader@1.1.8
npm ERR! node_modules/elm-hot-webpack-loader
npm ERR!   dev elm-hot-webpack-loader@"^1.1.8" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I looked at `elm-hot-webpack-loader@1.1.8` and it does reference `@"^7.0.1` for the dependent. Since it seems to be working for you is there around this error?

**Comment by roovo** [comment]
hmmmm, odd.  I just trashed my node_modules directory and re did `npm install` and all worked fine (and I don't have anything relevant install globally).  I have added an item on the todo list to verify on a separate machine.  In the meantime, I'd just put 7.01 in your package file and go with that.  I think it should be fine.

Anyone else having this issue??

**Comment by darthmachina** [comment]
I can confirm that downgrading to 7.0.1 allows `npm install` to run without issue for me. 

I'm using Archlinux and I did find that I have `elm-platform` installed from the AUR, and it is flagged as out of date since 2019-10-21, so that is probably what's going on with my local environment. I've never done anything with Elm so that was pulled in as a dependency of something, and I didn't even think of checking my installed packages.

Can probably chalk this up to a local environment issue and not an issue with the code.

**Comment by roovo** [comment]
Funnily enough I did get the same error this afternoon when I was messing around with the elm.json file, but didn't have the time to work out what was going on so I will still follow this to see if I can make it happen in my dev environment.

**Comment by roovo** [comment]
Have just done an install on a fresh machine and got exactly the same issue so have pushed the downgrade to the tech-debt branch ready for inclusion in the next release.

Thanks

**Comment by darthmachina** [comment]
Well, I'm glad I'm not going crazy then :). I had the downgrade stored locally but ignored for committing just in case it was just me.
