### ISSUE TITLE
[Support] Defined boards disappear if Obsidian refreshes or if CardBoard tab closed

### ISSUE THREAD

**Issue by hemicyon** [roovo/obsidian-card-board#124]
I’m not sure if this is a bug or if I’ve missed a step somewhere, but none of the boards that I make and define seem to save/store properly. If I close the CardBoard tab, or if Obsidian refreshes itself after it’s been in the background for a long while, all my previously made boards are gone from the list of boards, which means clicking on the CardBoard menu icon in the sidebar results in the prompt to add a new board for the first time again. So far, I’ve only been playing with test boards, and I can’t figure out what I’m doing wrong.

Obsidian v.1.4.1 (83)
iPadOS 16.1.1

**Comment by hemicyon** [comment]
It seems that another plugin (Kanban by mgmeyers) was in conflict with CardBoard. I disabled Kanban, and CardBoard now seems to be working as expected.

**Comment by roovo** [comment]
Thank you for the report and really glad you've got yourself sorted.  Strange that this happens, so I will keep an eye out for any similar reports :)   Thanks again and have a happy and prosperous 2023!

**Comment by kwosei** [comment]
Hi @roovo this exact behavior happens for me. In addition to the OP's reported behavior, another way to trigger defined boards disappearing is to click on the Cardboard launcher icon. You are taken to the setup screen and any defined boards are deleted.
