### ISSUE TITLE
[Bug] Subtasks with #at/ not working as expected

### ISSUE THREAD

**Issue by torstenkoepke** [roovo/obsidian-card-board#13]
Great work! 

But: The syntax #at/ on a tag board does not only include all subtasks like #at/PersonA and #at/PersonB/waiting (good!) but also #Matt and #atHome and all others with the original searched tag as part of their tag (not so good).   Could you please have a look at the regex you are using to identify the matching tasks?  

Thanks!

**Comment by roovo** [comment]
definitely not good - thank you for spotting - will take a look!

**Comment by roovo** [comment]
Have got it fixed - will be corrected in the next release (later today)

Thank you for spotting!
