### ISSUE TITLE
Support alternate task statuses

### ISSUE THREAD

**Issue by pcause** [roovo/obsidian-card-board#130]
The tasks plugin is adding support for [alternate statuses for tasks](https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/1530).  Support for alternate statuses would be a nice addition as cardboard and tasks are complementary.

If you could at least treat only items with an 'x' as completed it would help compatibility.  Many also use '-' for cancelled but just lower case x would be really useful.

**Comment by roovo** [comment]
Hi @pcause - and thanks.... I did see that Clare is working on this so you're right that this should bump up the priotrity for working on this in CardBoard....

I am going to close this issue as a duplicate tho - as I think it is covered in #122 (which I have just updated the title for to make it clearer what it is about).

I'll pop the link you have given for the issue in Tasks in there too so I dont' loose it.  Expect this to be suitably bumped up the priority stack :)

Thank you again
