### ISSUE TITLE
Confirm dialog for the Delete function in the Board columns

### ISSUE THREAD

**Issue by davebhc71** [roovo/obsidian-card-board#133]
Title says it all, especially for those of us who use iPads and have chubby fingers and TERRIBLE aim 😉 - please attached png
![10407B51-3777-4A24-A845-8E91E5217184](https://user-images.githubusercontent.com/80698092/215300154-e4edbd7d-cc05-40f5-9767-c260d5d8c3ec.jpeg)

**Comment by roovo** [comment]
Many thanks.  Added to the backlog.  In practice it will take a while for me to get to it as I want to have a go at getting drag and drop done first (which will be a pretty mammoth job).

Would having a way to undo an accidental delete instead work for you (say if there was an undo popup on the screen for a while after pressing the trash icon) instead?  Not decided which approach it better, the nice thing about providing an undo is it doesn't get in the way of the flow if the delete was intended.  The disadvantage is that you may not realise you didn't mean to delete the task straight away and so might miss the opportunity to undo.

**Comment by davebhc71** [comment]
Or…how about another UI choice for a column containing items recently Deleted (just like Completed)?!?On Jan 30, 2023, at 1:21 PM, roovo ***@***.***> wrote:﻿
Many thanks.  Added to the backlog.  In practice it will take a while for me to get to it as I want to have a go at getting drag and drop done first (which will be a pretty mammoth job).
Would having a way to undo an accidental delete instead work for you (say if there was an undo popup on the screen for a while after pressing the trash icon) instead?  Not decided which approach it better, the nice thing about providing an undo is it doesn't get in the way of the flow if the delete was intended.  The disadvantage is that you may not realise you didn't mean to delete the task straight away and so might miss the opportunity to undo.

**Comment by Angush** [comment]
Is deleting tasks a common action? Common enough to justify having such a primary, focused position? I've never done it intentionally, except when trying to create or edit tasks (which isn't a feature here anyway). I'd personally argue it's a tertiary action.

Some other ideas to provide a slight barrier to deletion, while still enabling it:

- The "Delete" action could be converted into an option in a context menu (ie. right click a task, or long press on mobile).
    - I believe Obsidian has [an API for context menus](https://marcus.se.net/obsidian-plugin-docs/user-interface/context-menus). Not sure if it supports mobile devices though.
- With drag-and-drop, a "trash" section could appear when a task is being moved, and delete any items that are dropped onto it.

**Comment by davebhc71** [comment]
I like your 1st action of either right click with mouse or long press with finger. Either is more ‘intentional’ than accidentally (big finger syndrome) hitting the Delete button. I’m not opposed to Trash, either.

**Comment by roovo** [comment]
Thanks both ...I do find myself using delete enough that I want to keep it as an easy thing to do; I periodically review tasks (being a master of procrastination they can build up) and often find myself using delete to get rid of things I am prob not going to get done for some reason or another.  I guess the frictionless-ness of this for me when doing this is the gain against the pain of fat fingering or wanting/needing to undo :)

Definitely up for doing something here and some interesting ideas !!

**Comment by davebhc71** [comment]
you giving it some thought is good enough for me!

**Comment by roovo** [comment]
Going to pick this up next.  Am going to add a delete confirmation dialog as this is the most straightforward to implement.  I do like the idea of including a delete column, but this will have to be saved up for a later day as it will involve quite a bit more thought and work (parser changes - eek).

**Comment by roovo** [comment]
Just released version 0.7.6 - there is now a confirmation dialog step when deleting cards. I will create a separate issue to keep the idea of a recently deleted column alive.
