### ISSUE TITLE
Dates in filenames are recognized as Due Dates

### ISSUE THREAD

**Issue by schniewmatz** [roovo/obsidian-card-board#139]
Dear @roovo first of all thank you for the great work, I really like using it to build a combination of bullet journaling and getting things done in Obsidian :)

I use Daily notes which have simply a YYYY-MM-DD formatted date as filename.
I collect all kind of notes and tasks in these daily notes. Some tasks have a due date assigned others do not and are e.g. tagged "#somewhen".

CardBoard seems to assign the date from the filename to the tasks without date, which renders it rather useless for me currently as the whole today section is spammed with tasks that actually have no date and are simply recorded to do them maybe sometime in the future.

I use the current version of your plugin and additionally the Tasks Plugin, as well as the Dataview Plugin.

**Example:**
In a file named *2023-02-02*:

```markdown
- [ ] Task 1 #projectA #next 📅 2023-02-10
- [ ] Task 2 #projectA #somewhen
```
TaskBoard shows them like this (on the 1st of Feb.)
![grafik](https://user-images.githubusercontent.com/30618024/216118048-01c00c4a-d2db-4d64-b530-9ee8d83b307d.png)

**Comment by schniewmatz** [comment]
Ah just realized I apparently was searching for the wrong keywords. It is already in progress for 0.7.2 (#106 )
But now it is a bug, so it might get a high priority? 😁 

So anyway:
![Thanks](https://media.giphy.com/media/KJ1f5iTl4Oo7u/giphy-downsized-large.gif)

**Comment by roovo** [comment]
Hiya - and thanks ....yep - hope to look at this over the weekend.  My plan is to:

- add an option for date boards to ignore filename dates
- make it so if you put @due(none) on the line of a task it will ignore the date for that single task.

Not sure if I'll have time to get it finished this weekend, but I'll do my best and it shouldn't be too much after if I don't :)

Thanks again.  I'll leave this issue open till I've done it so you can keep track easily!

**Comment by roovo** [comment]
current plan is to:
- add an option to global settings to not use daily note file names when setting the due date for tasks. I was initially thinking of doing this on a per-board basis, but that could lead to cards appearing on different boards with different due dates which doesn't feel desirable.
- allow https://github.com/Due(none) to be placed on a task line to nullify the due date derived from the file name. This is needed for drag and drop so that a task in a daily note can be moved to the undated column.

**Comment by schniewmatz** [comment]
This makes sense to me :)

**Comment by roovo** [comment]
...and version 0.7.2 is now out which supports this :)  There's a new global setting, plus I've added support for `@due(none)`.  Any issues with it, just let me know.  Many thanks :)

**Comment by schniewmatz** [comment]
Works like a charm, tank you!
