### ISSUE TITLE
[Feature Request] Overdue tasks?

### ISSUE THREAD

**Issue by torstenkoepke** [roovo/obsidian-card-board#14]
I am not able to find the spot where the tasks I failed to accomplish yesterday and even before yesterday can be found? I would see a natural spot in the first column of the Date on the left of the Today column. 

Am I missing something here, are they perhaps automatically moved to today going forward?

**Comment by roovo** [comment]
Hi @torstenkoepke 

Thanks for asking.  They should appear at the top of the Today column above any tasks that are actually tagged for today.  The idea being that it will get steadily more annoying to see what you were planning to do today if you have a lot of incomplete tasks from previous days (my work board from my day job is like this).  Hope this makes sense.

I'll add something to the README to make this clear.

Thanks again

[closing, but feel free to re-open if needs be]
