### ISSUE TITLE
When setting up a new tag board, unable to scroll in filter definitions dialog box

### ISSUE THREAD

**Issue by sgsvaya** [roovo/obsidian-card-board#146]
When I try to create a new tag board, I click on Definitions in the filter section and get a popup list and I'm not able to scroll down the list beyond the first suggestion under tags. This works fine when creating a date board. I'm on a Macbook Pro running MacOS 13.2.1.

![image](https://user-images.githubusercontent.com/93988228/221515884-9924095e-922d-43cc-ac6a-b43e04e897a8.png)

**Comment by el3um4s** [comment]
I have the same problem on my Windows 10 PC

**Comment by liesecarleton** [comment]
I have the same issue, Windows 10. I can't get to my list of tags at all.

**Comment by roovo** [comment]
[note to self] can reproduce by creating a date board in my example vault - then clickm in the definitions box

**Comment by roovo** [comment]
I've made the dropdown slightly bigger and (more importantly) it is now scrollable :)  see version 0.7.6
