### ISSUE TITLE
Defined tags showing up in Others

### ISSUE THREAD

**Issue by tb-1212** [roovo/obsidian-card-board#149]
Hi, not sure if I'm doing it right but

when i define a tag Todo/ Todo
it shows all tags in the column Todo
Todo/1 
Todo/2
Todo/3

but in the Others column they also show up, is there a way to have them not be shown in the Others column if its already in the Todo column?

**Comment by roovo** [comment]
Hi there.  No, you weren't doing anything wrong - there were issues with placement of cards in columns if an _Other Tags_ column was on a board.  I (hope I have) fixed this in the latest release (0.7.6).  Do let me know if there are still problems!

Many thanks
