### ISSUE TITLE
How do I add a new board?

### ISSUE THREAD

**Issue by L0ll094** [roovo/obsidian-card-board#157]
Hi! I made a date-based board but would also like to see my todos in a tag-based board. Is that not possible? I can see no"+" or add board option, but the current board looks like a tab (implying there could be more tabs). I hope this is a silly question and I'm missing something obvious.

**Comment by roovo** [comment]
![Screenshot 2023-12-30 at 17 03 40](https://github.com/roovo/obsidian-card-board/assets/5251/3b0d2617-e3e2-4529-b7a4-87a51763bc4c)

Hope this helps - this is where you need to click to see the settings and where the '+' icon is to add a new board

**Comment by roovo** [comment]
I've updated the README to include this - will be visible on github when I next release (should be very soon)
