### ISSUE TITLE
Adding Compatibility to alternative checkboxes

### ISSUE THREAD

**Issue by kaletellier** [roovo/obsidian-card-board#161]
When using alternate checkboxe style like the css snippets of SlRvb, the checkbox-tasks won't appear in the card board.
It would be awesome having different types of checkboxes also appearing in the card board to differantiate or categorize such to dos.

P.S.
I really love the card board plugin! Thanks!

**Comment by roovo** [comment]
Hiya and thank you.  I am actually tracking this on #122 (which I have just updated the title of to make it a bit more obvious that this covers custom checkboxes.

I will close this as a duplicate, so please add to and/or follow #122 to track - it will be a while before I start to think about this as "the great drag and drop feature" is going to be taking up much CardBoard dev time for a while tho.

Thank you again
