### ISSUE TITLE
Cardboard broken in Obsidian 1.3.7?

### ISSUE THREAD

**Issue by benpocalypse** [roovo/obsidian-card-board#162]
First - I love your plugin for Obsidian, I've been using it for years at this point.

I haven't had a chance to use Obsidian for the last few weeks, so I'm not exactly sure when this broke, but when I opened it this morning after updating to 1.3.7, it appears that the display for Cardboard is broken. The settings all work, but Cardboard doesn't seem to want to display either of my 2 Cardboard boards.

See attached screenshot.

![Screenshot from 2023-08-01 10 15 33](https://github.com/roovo/obsidian-card-board/assets/6274196/2db268f6-7481-47f2-96fa-3692f68b6ded)

I'm more than willing to attach any debugging information or test anything out that might help - just let me know. I really appreciate that this is a spare time project (lord knows I have too many of those myself) so I'm not expecting a timely resolution, I just wanted to help.

**Comment by gazattack** [comment]
FWIW I just upgraded to 1.3.7 and my single Cardboard board works great still.  Just created a second board to make sure it's not a multi-board issue, and that one seems to work fine too.  Sorry I can't be more help :-(  Maybe it's an interaction with another plugin?

**Comment by benpocalypse** [comment]
Cardboard is the only community plugin I have installed - but if it works for you, then it must be something on my end. I'll see if I can't just start a new vault, reset my settings to default, and hopefully that does the trick.

Thanks for the datapoint @gazattack

**Comment by benpocalypse** [comment]
Yup, creating a new vault seems to fix the issue. I'll be able to figure this out on my end, I'm going to close this ticket then.

![image](https://github.com/roovo/obsidian-card-board/assets/6274196/0228a05c-7a19-422e-a764-adee047e7f1a)
