### ISSUE TITLE
Untagged task with subtask goes to Completed instead of Others

### ISSUE THREAD

**Issue by SabreCat** [roovo/obsidian-card-board#165]
**Issue:** Using a tag board, a task that meets the filter definition for the board, but lacks a tag to assign it to a specific column, shows up as Completed if it has any subtasks.

**Steps to reproduce:**
1. Create a new Board of "Tag board" type.
2. In the Filters Definitions field, add a tag.
3. In the Columns Definitions field, add a few tags and column headings.
4. Turn on "Include others".
5. Elsewhere in your vault, create a task with the tag from the Filters Definitions.
6. Check the board. The task shows up in the Others list.
7. Go back to the task, then start a new line and indent it, creating a subtask.
8. Check the board. The task shows up as Completed.
9. Go back to the task, and add a tag from the Columns Definitions.
10. Check the board. The task shows up in the assigned column.

If the "Others" column is hidden, the task does not show up in Completed.

**Comment by SabreCat** [comment]
![image](https://github.com/roovo/obsidian-card-board/assets/4501321/2539b331-f2a4-4071-a4eb-c7a090d2d20f)

**Comment by SabreCat** [comment]
Possibly related: a task with a tag but without subtasks shows up in _both_ the Others column and its tag column:
![image](https://github.com/roovo/obsidian-card-board/assets/4501321/9f4b0092-73c6-4f26-88d2-bcf7d477c749)

**Comment by roovo** [comment]
Righty-ho, I think I have this fixed in the latest release (0.7.6).  If you find any more strange behaviour, do let me know!

Many thanks
