### ISSUE TITLE
Option to organize past-due cards in dedicated columns on a card board?

### ISSUE THREAD

**Issue by craigconstantine** [roovo/obsidian-card-board#167]
Could there be a setting to organize past-due cards in dedicated columns on a card board? If this is enabled, then instead of having everything which is past its due-date on the Today column.

This could add 3 new columns…
- "Last Week" for anything due before today, within the last 7 days
- "Last Month" is before "last week" and within 30 days
- "Older" is before 30-days-ago

This would make it possible to toggle open/closed different columns to visually focus on "past", "present", and "future" todo cards.

I can imagine a complex system for adding/configuring multiple "past-due columns"—but I don't think that's necessary. Having just a few past-due columns in the spirit of the current "Tomorrow" and "Future" columns would be useful.

**Comment by roovo** [comment]
Hi - I am currently working on providing more flexibility in choosing columns for date based boards - tracking at issue: #93.  This may well offer what you need!

**Comment by roovo** [comment]
Hopefully the latest release (0.7.5) will do what you need - you can create your own custom date based columns based on relative dates :)
