### ISSUE TITLE
Obsidian freezes when clicking plugin's icon for the first time

### ISSUE THREAD

**Issue by ulimueller** [roovo/obsidian-card-board#169]
I just installed the plugin, so I have not yet any boards defined. When I hover the icon in the app ribbon, a tooltip saying "cardboard" appears. When I click the icon, the whole app freezes. No other way to get out than killing it wih the task manager.

I am using Obsidian 1.4.14 on Windows 11

**Comment by qdominik** [comment]
I have similar issue with frozing Obsidian by clicking CardBoard. In my case there was a conflict with another community plugin. You can try swich off all plugins, and then turn it on one by one to find if there is a conflict.

**Comment by ulimueller** [comment]
The problem seems to be caused by the folder index plugin. There they report similar incompatibilities with other plugins and functions too.

E.g. https://github.com/turulix/obsidian-folder-index/issues/58

**Comment by roovo** [comment]
looks like there has been a fix applied to the folder index plugin.  I did just check in a fresh vault and CardBoard seems to open fine when the Folder Index plugin is present.
