### ISSUE TITLE
Support tasks in callouts

### ISSUE THREAD

**Issue by jdjshhc** [roovo/obsidian-card-board#183]
Unable to retrieve to-do information in callout
![image](https://github.com/roovo/obsidian-card-board/assets/106785928/dff7b94c-219f-41f1-a64c-f0368da2b71d)

**Comment by jdjshhc** [comment]
![image](https://github.com/roovo/obsidian-card-board/assets/106785928/49b096b7-f2f7-473d-8a31-8819ed612796)

**Comment by roovo** [comment]
closing as duplicate of #142
