### ISSUE TITLE
Other tag column issues (检索信息显示的问题)

### ISSUE THREAD

**Issue by lxmwwl** [roovo/obsidian-card-board#184]
大佬，这次我发现两个问题，一个是拥有两个以上数目标签的任务无法展示"其他标签“的看板里区分开，还有一个问题是含有子任务的任务也无法在展示“其他标签”的看板里显示出来。

**Comment by roovo** [comment]
Translated by google as (for my reference)

I found two problems this time. One is that tasks with more than two tags cannot be distinguished in the "Other Tags" display board. The other problem is that tasks with subtasks cannot be distinguished in the "Other Tags" display. ” is displayed on the tagboard.

--------
I have found some additional behaviour I want to review around the Other Tags column so will review this all together....

**Comment by roovo** [comment]
also need to review #165

**Comment by roovo** [comment]
please try the latest release - 0.7.6.  I have (hopefully) fixed these issues.  Please do let me know if you do find any further problems with this.

Many thanks
