### ISSUE TITLE
Need to reload date board next day

### ISSUE THREAD

**Issue by roovo** [roovo/obsidian-card-board#185]
as if cards move between columns due to a change in the day their contents are blank when they are in the new column

**Comment by ty-lab** [comment]
Hi bro, thanks for you developing this plugin, there is an issues that need to be solved, the **future card** is not correctly recognized when the due date of a task crosses the year

**Comment by roovo** [comment]
@ty-lab -> I've added a separate card for the issue you raised: #188

**Comment by roovo** [comment]
@ty-lab -> my assumption here is that this is an issue of what is displayed on a card rather than with ifcards appear in columns or not.  My fix is to show the date on the card if it is not in the current year:

![Screenshot 2024-01-05 at 09 20 47](https://github.com/roovo/obsidian-card-board/assets/5251/69de61b8-2932-4e94-895f-4a494b6c85f1)

This will be in the next release (which will close this issue).  If this isn't what you meant, it would be really handy if you add a comment on #188 to explain.

Many thanks

**Comment by roovo** [comment]
...and released - 0.7.6
