### ISSUE TITLE
[Suggestion]You could use a private API to scroll to specific text

### ISSUE THREAD

**Issue by Quorafind** [roovo/obsidian-card-board#2]
https://discord.com/channels/686053708261228577/840286264964022302/882336266228748318

![image](https://user-images.githubusercontent.com/13215013/139536823-0a615ef4-c284-458c-a130-1bcde3413c78.png)

`leaf.openFile(file, {eState: {match: {content: originalTextContent, matches: [[start, end]]}}});`

Which might be better than add a block reference to a text?

**Comment by roovo** [comment]
That looks cool - thanks - really appreciated, will have a play and see what I can do - it'd be great not to be adding block references (and cut out a hacky sleep I have in the code too :)

**Comment by roovo** [comment]
OKay, so I've had an initial stab at this and have come up with a solutiuon (that doesn't quite work yet), based on your suggestion coupled with the code from [obsidian-community-lib#openOrSwitch](https://obsidian-community.github.io/obsidian-community-lib/modules.html#openOrSwitch) so it opens the file in either an existing leaf or in a new one if it isn't already open.

I'm then using leaf.setEphemeralState({ line: lineNumber }) to set the highlight on the line of the todo title.  This works when the file is opened in a new leaf, but not when it is in an already opened leaf.  This is where it is not working:

https://github.com/roovo/obsidian-card-board/blob/b625c5028d5945a6b8c5194e8ba6e8e97568c5fa/typescript/view.ts#L213-L214

I have ended up lost in the logic, as it is actually highlighting the correct line in the file and then eventually it ends up in the line inside the `t.prototype.onDocumentClick` function:

```javascript
t.prototype.onResize = function() {
    this.trigger("resize")
}
,
t.prototype.onDocumentClick = function(e) {
    e.defaultPrevented || this.trigger("click")
}
,
t.prototype.onLinkContextMenu = function(e, t, n, i) {
    var r = new Uv(this.app);
    this.handleLinkContextMenu(r, t, n, i) && (e.preventDefault(),
    r.showAtMouseEvent(e))
}
```

This triggers the click and the highlight goes away - hmphh

This will be really cool if I can get it working as I could change it later to highlight all the lines for a task with subtasks and whatnot underneath it, so am determined to get this fixed, but may need some help working out why it is doing this (and what I need to do to stop it).  So if you have any ideas......

I've been stepping through javascript long enough for today tho 😵‍💫

**Comment by roovo** [comment]
Think I have it working so will hopefully be incorporated into the first (non-beta) release - *yay*

**Comment by roovo** [comment]
A big thanks @Quorafind - a massive improvement not having to write block links 😄 .  Code is that little bit sweeter now too!!
