### ISSUE TITLE
Issue with minimal theme

### ISSUE THREAD

**Issue by fpopineau** [roovo/obsidian-card-board#202]
Hi,

I just discovered cardboard and I like it very much.
I hit a display problem with the minimal theme where I can't add a new board because there is no button:
<img width="195" alt="image" src="https://github.com/roovo/obsidian-card-board/assets/1915631/dc7d0485-f3c3-4141-b10a-618b70cf0f11">

With the default theme, I get the line and the button:
<img width="189" alt="image" src="https://github.com/roovo/obsidian-card-board/assets/1915631/fbef94d4-dfea-4856-b7b1-bf311604e1e8">

Regards,

Fabrice

**Comment by roovo** [comment]
thanks Fabrice - I have previously had someone asking about how to create a board, so am wondering if they were also seeing this probelm.  However, II'm having problems replicating this as the button is visible in my vault.

I tried in a new vault with just the minimal theme and cardboard installed and I can see it there too.

I see that there are a huge number of configuration options for the minimal theme in style settings so if it is something hidden in there it could be pretty hard to uncover what is happening.

**Comment by fpopineau** [comment]
Oh ... It's good to know that it can work! So, I'll keep digging with the minimal configuration and see if I can come up with a reason why this button may become invisible.
Pity that is it difficult to debug those dialog boxes.
In the meantime, it would be nice if you could add a command to create a new cardboard :)

**Comment by roovo** [comment]
Thank you - I will certainly take a look if you manage to find anything.

Thinking about it, one thing you could try (if you fancy doing some detective work) is using the developer tools in the vault where the + button isn't showing up...  If you open the CardBoard setting dialog and toggle the developer tools in the obsidian view menu:

![Screenshot 2024-02-11 at 20 15 05](https://github.com/roovo/obsidian-card-board/assets/5251/01a2ea60-fc4e-4927-ab89-d3d705d91f78)

The header-group-title line should open showing the header-group-title-icon line:

![Screenshot 2024-02-11 at 20 30 20](https://github.com/roovo/obsidian-card-board/assets/5251/bd113c11-0504-4135-a777-7827c1e2da70)

You may be able to see what is happening.  The icon will likely either have moved somewhere else, or it may have been made invisible.  Depending what your css skills are like you may be able to work out which of these has happened (could be both) and what line in the styles section is causing it to happen (could be more than one).

**Comment by roovo** [comment]
on the adding a command - I plan on greatly simplifying the settings pane after I have done drag and drop by making most of the settings for each part of the board available directly via the normal interface.  As part of this, the board creation button will move to main board view - which I guess may or may not solve this issue depending on what it is that is actually happening.

Interesting idea on adding a command - will have to think about how that might work!

**Comment by fpopineau** [comment]
> Thank you - I will certainly take a look if you manage to find anything.

You can close the issue. Thanks to your detailed explanations (I did not find out how to use the debugger on the popup), I was able to find that --text-faint (which in turn was some --tx3 color) had the bad luck to coincide with some local choice of color I applied. All in all, the text was there, beige on beige :-( After resetting all theme settings, both in Minimal Theme Setting and in Style Settings, all is good.

Keep up the good work ! Thanks again.
