### ISSUE TITLE
[Feature Request] Would it be nice to have a new board kind like project?

### ISSUE THREAD

**Issue by Quorafind** [roovo/obsidian-card-board#22]
# WHY

It will be nice to have a board to track all tasks in a project though they are living in any daily notes.

# HOW

All tasks in a folder or marked a tag would be listed in a cardboard, and then we could manage it.

A mock up below:

![image](https://user-images.githubusercontent.com/13215013/139612303-78d28f9d-ee9c-4631-91bc-b2027f1b4470.png)

# Another Way to do it

We could have a setting to allow it track only one tag,  OR all tasks in folder.
 
Like date board in a specific folder OR tag board with a specific tag.

**Comment by roovo** [comment]
I like this idea!  Will implement - not sure when as still waiting to see what feature requests come in as people start using it.

If I've understood what you mean then it would make these additional options for the date board so you could choose to filter the tasks that appear on it by either/both folder and/or tag, so you would still have a date based board but it would be based on a sub-set of your tasks.

Love it!

**Comment by Quorafind** [comment]
Nice conclusion, a filter must be a game changer for me . Can't wait to see it.

**Comment by darthmachina** [comment]
I'm wondering if a combination of #21 and #27 (if it became a full include/exclude list) would automatically get us this request. Not sure if a board pulled from a static tag vs. the ad-hoc filtering that #21 gives us would better satisfy the use case or not, though.

**Comment by roovo** [comment]
My thinking here is that:

#27 will be a global setting where directories and/or files can be entered into an ignore list.  Anything specified in here will not be parsed into the TaskList held in the Model. So whatever is in here will apply whatever is set on any individual board.

The stuff in here (#22) will be a per board setting (for both types of board) and will control what appears on that specific board (within the constraints of anything in the global setting above)

#21 will be something that will not affect the settings in the same way - it will purely be a way to filter the view you are seeing at the moment in a more temporary way.  I am even thinking that it should allow you to switch boards "underneath it" and it would keep it applied to whichever board you are currently viewing.

Does that make some sort of sense?  These feel like a sensible set of options to give more power to the boards without over-complicating things - and I want to try and keep things as straightforward and simple to use as possible...

**Comment by darthmachina** [comment]
That setup makes total sense! I'm good with that distribution of features..

**Comment by roovo** [comment]
@Quorafind - just added filters in the latest release 0.3.2. Hope it works for you!
