### ISSUE TITLE
[Feature Request] Add tag name to CSS classes for a tag

### ISSUE THREAD

**Issue by darthmachina** [roovo/obsidian-card-board#24]
I definitely like having visual clues on the board. As part of that I have a couple tags related to areas of my life that I have color coded. I currently have a snippet that colors these for me. I was wondering about adding a CSS class to each tag that includes the tag name. So for a tag named work the CSS class would be `tag-work`. Since tags can have a hierarchy (`parent/child`) my thoughts there were to replace `/` with `_`.

I was going to try my hand at coding up my own change for this and was thinking I would try to make this change and submit a PR for it.

**Comment by roovo** [comment]
wonderful idea - and thanks for the PR - it's my first 😄.  Will review later today and create a beta release which should be install-able with BRAT.

**Comment by roovo** [comment]
Merged the PR - will be in release 0.2.0-beta v.soon - thanks

**Comment by darthmachina** [comment]
For anyone coming here looking on how to accomplish this, the following CSS snippet will change the background and text colors for a tag named `test`:

```
.cm-s-obsidian div.tag-test > span.cm-hashtag {
  background-color: #FFFFFF !important;
  color: #000000 !important;
}
``` 

There is probably a way to select the element in a better way to not require the `!important` modifier but this works for now. You can use variables here from the theme or Obsidian if you want, like `var(--color-blue-6)`.

**Comment by roovo** [comment]
Have added this to the Readme too: https://github.com/roovo/obsidian-card-board#customising-tags
