### ISSUE TITLE
[Bug] Due dates incorrect when task pulled from Daily Page

### ISSUE THREAD

**Issue by darthmachina** [roovo/obsidian-card-board#28]
Just noticed this one and it's getting late, I can add more detail later but wanted to submit this while it was fresh.

I have some tasks that I put on the daily page for November 2nd (titled `2021-11-02`), but the date listed on the card says `Due: Fri, Nov 1st`. I'm guessing the `Nov 1st` thing is because of a timezone shift since I'm US Central so hours get subtracted, which would be from midnight on 11-02. However, I have no clue where the `Fri` is coming from.

Since it's after midnight here I created my Daily Page for today (`2021-11-03`), and the due date is showing `Due: Sat, Nov 1st` now. So the day of the week changed but not the date.

I am using the core Daily Notes plugin at the moment, though I do have Periodic Notes installed but not enabled.

**Comment by roovo** [comment]
That is odd - I can't replicate in my vault.  If you create a new vault (with the same daily note settings) and try it there are you seeing the same behaviour?  Not that which vault it is in should matter, but if you are you could zip up the empty vault and send it to me so I can see what's happening if it happens for me too.

I'm totally baffled why it would be showing the wrong day for the date!!

**Comment by darthmachina** [comment]
I was able to reproduce this in my test vault. Seems it's my Date Format setting for the daily notes as I have it create folders for the month: `YYYY-MM/YYYY-MM-DD`. Not sure what's going on in the code, though, as I haven't investigated there. I switched it to just `YYYY-MM-DD` and after refreshing the board the dates showed up correctly.

I'm attaching the test vault but just changing the date format should be enough.

[28-test-vault.zip](https://github.com/roovo/obsidian-card-board/files/7468020/28-test-vault.zip)

**Comment by roovo** [comment]
Got it fixed.... I was working out the date in my own code in view.ts, one of my tidy-up tasks was to switch to using liamcain's obsidian-daily-notes-interface.  This has a function in it for getting file dates so I've used this instead and it's now working - yay to liam :)

I'll push it to the main branch in a few mins - thanks for spotting this!

**Comment by roovo** [comment]
will be in the next beta (and main) releases -> closing with thanks
