### ISSUE TITLE
[Feature Request] New Board: Headers Board -> tasks under the Headers of a Specific File

### ISSUE THREAD

**Issue by FelipeRearden** [roovo/obsidian-card-board#3]
Hello @roovo !!!!!

First of all, I just wanna say thank you for using your time to create such a great plugin :)
I must say what a great first release :) It's so good to see a first beta so polish and ready to use :)

I'd like to share with you my FR: it's a new type of Board for the tasks which is based on two things:
 1.   All tasks from an specific file 
 2. All tasks from an specific file + using the Headers as a criteria to split the tasks in the cardboard

## My Workflow for Projects

For many of my workflows I have an specific folder that concentrates all notes/resources related to that Project.

One of the notes is a tasks/todo note that I is placed in the left sidebar to look when I need (I have a hotkey to open/close this note in the sidebar)
- Keeping a unique note is useful when adding new projects that have the same (or most of the same) tasks structure.

The structure of this note is based on headers. Each header have tasks that have the same principle/meaning:

```
## Header A
- [ ] item_1A
- [ ] item_2A
- [ ] item_3A

## Header B
- [ ] item_1B
	- [ ] item_1B.1
	- [ ] item_1b.2


## Header C
### Header C1
- [ ] item_1C
- [ ] item_2C

### Header C2
- [ ] item_1C
- [ ] item_1C

```

As you can see, for these projects I just use simple tasks (without dates and tags)

## MY FR

**1.Create a new board based on a specific file**

**2. Headers will be used as a criteria to split the tasks inside the cardboard**
- each header have the same visual formatting 
- there no difference from an H1 and a H3  

This image tries to show what i'm thinking :)

without the tags :) 

![0](https://user-images.githubusercontent.com/85180696/139553883-17473c64-6da4-48dd-a60b-f6349735b20d.png)

---

Thank you very much for readings this. I hope you like my suggestion 🙏🙏🙏

Let me know if you need more information

**Comment by roovo** [comment]
Hi Felipe

many thanks for taking the time to put this FR together.  Loads of detail, so I totally understand what you're after and would love to get something like this into a future release.

As I am parsing the markdown files myself in the plugin and hadn't got this idea in mind when I wrote the parser, it will not do it at the moment as it has no concept of headings built-in, so it will be a bit of work to implement but it is certainly do-able.  And it is something I would like to do too!

I'll wait and see what other requests come in when it has been used in the wild a bit more then make some sort of priority call on what would make a sensible priority order for feature requests that are going to take some work to implement.

I'll update here later (soon), in the meantime if anyone else would like to see this, then please give it a 👍 or something!

Thank you again - and for the encouraging words - very much appreciated

**Comment by FelipeRearden** [comment]
Hello @roovo !!!!!

Thank you so much for your reply! I'm glad to know that FR makes easier for you to understand my idea :)
- I believe that is a duty to the user/tester to write an FR that have detailed information about the topic/feature that the person is requesting :) 

And very excited to know that is something that you would love to do in the future. Great!!!!!

> As I am parsing the markdown files myself in the plugin and hadn't got this idea in mind when I wrote the parser, it will not do it at the moment as it has no concept of headings built-in, so it will be a bit of work to implement but it is certainly do-able. And it is something I would like to do too!

Good to know that is an FR that is doable ! Many times we have some crazy idea that is not feasible. I'm happy to know that is something that you would like to do!

> I'll wait and see what other requests come in when it has been used in the wild a bit more then make some sort of priority call on what would make a sensible priority order for feature requests that are going to take some work to implement.

Sure! Let's see how our community friends will use this amazing plugin and wait for new ideas and FR. 
- We are so excited on Discord since your post that I know that will be an amazing ideas :)

Tomorrow I will start to using the Tag Board properly. I already have two QoL FR that I will bring to you tomorrow (because I want to test a little bit more before bring to you)

> I'll update here later (soon), in the meantime if anyone else would like to see this, then please give it a 👍 or something!

Great. thanks! 👍

> Thank you again - and for the encouraging words - very much appreciated

Thank you very much for your kindness @roovo and to your attention to my FR ! It's a pleasure talking to you for this first time! 

Welcome to our community :)

I wish you a fantastic day!!!!!!!!

**Comment by roovo** [comment]
Hi @FelipeRearden 

> Tomorrow I will start to using the Tag Board properly. I already have two QoL FR that I will bring to you tomorrow (because I want to test a little bit more before bring to you)

Whilst I think of it I have added a note to the README for Tag Boards on how they work with sub-tags.  Basically If you specify a tag with a trailing `/` then the column will contain all sub-tags of the tag (so `foo/bar/` will include any tasks tagged with `foo/bar` as well as tags such as `foo/bar/baz`.

Cheers

**Comment by FelipeRearden** [comment]
> Whilst I think of it I have added a note to the README for Tag Boards on how they work with sub-tags.  Basically If you specify a tag with a trailing `/` then the column will contain all sub-tags of the tag (so `foo/bar/` will include any tasks tagged with `foo/bar` as well as tags such as `foo/bar/baz`.
> 

Thank you very much @roovo !!!! 

The README.md is great! 100% crystal clear on how to set a Tag Board. 


Thanks again! 

Have a great day!

**Comment by roovo** [comment]
There was a but in how I picked cards to display under a tag (#13) - fixed in the latest release (0.1.0) so you might want to grab that :)

**Comment by FelipeRearden** [comment]
> There was a bug in how I picked cards to display under a tag (#13) - fixed in the latest release (0.1.0) so you might want to grab that :)

Thank you very much for this information @roovo !!!!!

Updating right now !!!!!!!

**Comment by roovo** [comment]
Now that I have gone for a first release I have had a little more of a look around what some of the other task management plugins actually do and it looks like the [kanban plugin](https://github.com/mgmeyers/obsidian-kanban) might already have a lot of what you need for this type of board.  Have you had a look at using this?

**Comment by FelipeRearden** [comment]
Hello again @roovo !!!!

Thank you very much for remembering about Kanban! 

I do know about kanban but I didn't remember that it uses `header` as the criteria for the columns.
- In my mind kanban uses `<ul>` as the criteria for the columns. But I was wrong :)

```
<ul> <li>Header A <ul>
      <li>Item 1A</li>
      <li>Item 2A</li>
    </ul>
</ul>


```  

You are right!!!! Kanban works perfect for my workflow since every header has a task in this specific note!
- I'm gonna start to use to see if fits well :)


## Just one Comment 

In my opinion. one of the most amazing feature of Cardboard is the ability to have more than one board inside the cardboard:
- That's a big difference from Kanban with is a Kanban note for each file/note;
- With cardboard we can have multiples kanban in the same cardboard!

In my mind, I imagine my cardboard with at least with 5 boards:
1- By Tag 
2- By Specific File 1 -> I have a note with a list of tasks/thing that I wanna do in the future without any schedule;
3- By Specific File 2 -> Project A
4- By Specific File 3 -> Project B
5- By Specific File 4 -> Project C

One Hotkey to open this master Cardboard -> #6 
One hotkey to navigate between each board -> #7 

---

Kanban is a great idea and I have to say thank you to you, because I almost lost this one :)

@roovo feel absolutely free to close or postpone this FR the way that you feel more comfortable :) 
- In my humble opinion, besides Kanban, I still believe that a Board based o Headers and specific files would be a great addition to this fantastic plugin!


I wish you a fantastic day!

**Comment by roovo** [comment]
Hi

really glad that it looks like it will meet your needs - obviously feedback to  @mgmeyers where needed.  I will close this FR (with thanks) - I have added a line in my TODO file referencing back here so the thought won't be lost!

If I resurrect it I will let you know & have a fab day yourself :)

**Comment by FelipeRearden** [comment]
Hello @roovo !!!

Okay! Thanks for all attention with my FR :)

Let keep talking :)

Thanks, have a great day too!
