### ISSUE TITLE
[Bug] Same tag on two different subtasks gets added to card twice

### ISSUE THREAD

**Issue by darthmachina** [roovo/obsidian-card-board#33]
I like the idea of pulling in tags on subtasks so they appear on the card as a whole, but it looks like there is no duplicate detection. So adding the same tag onto multiple subtasks will add that tag to the card for each subtask where it's set. The tag should only be put on the card once and ignored any other time it's used.

In tech speak: the tags on the card should be a set and not a list so it won't allow duplicates.

**Comment by roovo** [comment]
Nice spot - to be fixed in the next release - thanks :)
