### ISSUE TITLE
[Feature Request] Remove Status tag from tags shown on the card

### ISSUE THREAD

**Issue by darthmachina** [roovo/obsidian-card-board#5]
On a Tag-based board it would be nice to not show the associated tag on the card, since that is basically duplicated information. This will reduce the visual clutter on the cards

**Comment by roovo** [comment]
Makes total sense - thanks.  Think I should be able to add this is an early-ish update :)

**Comment by amurena** [comment]
Is this is in the most recent build? I'm still seeing this as an issue on the tag board.
