### ISSUE TITLE
Collapsible Columns

### ISSUE THREAD

**Issue by darthmachina** [roovo/obsidian-card-board#50]
I'll start by saying this is probably a candidate for #42 :). Just wanted to get it out there.

It would be nice to be able to "hide" a column. My task workflow includes a number of columns, not all of which are relevant all the time. It would be nice to be able to hide those columns but still have access to them if needed.

The mock-up has the idea of having an arrow by the heading which will hide the cards, narrow the column and rotate the title. Clicking the arrow again will put the column back to it's normal state.

If you're familiar with Trello at all this would duplicate the Chrome extension [Collapsible Trello Lists](https://chrome.google.com/webstore/detail/collapsible-trello-lists/kejemfjfgoaekplmemlkjljcfloiemho)

![image](https://user-images.githubusercontent.com/3865380/141605049-7d4f873c-3a42-4b35-a83a-c9f6323d617f.png)

**Comment by roovo** [comment]
Auto-hiding of empty columns could be a good option too!

**Comment by roovo** [comment]
Auto-hiding made things less intuitive so scrapped this idea in the end and just went with vanilla hiding!
