### ISSUE TITLE
[Bug] "#foo:x" is parsed as a tag where Obsidian only recognizes "#foo" as the tag

### ISSUE THREAD

**Issue by darthmachina** [roovo/obsidian-card-board#56]
The parser for tags treats `#foo:x` as a tag but Obsidian only recognizes `#foo` as the tag. The parser should be adjusted so that is treats `#foo:x` as `#foo`.

**Comment by darthmachina** [comment]
Just to comment here as a follow-up to a question I had for roovo, there are other characters that cause Obsidian to stop parsing the tag but CardBoard will still pick it up (`!` being one of them). Going to see if I can find a list of these to account for all of them in one go.

**Comment by roovo** [comment]
fixed in [release 3.3](https://github.com/roovo/obsidian-card-board/releases/tag/0.3.3)... thanks for the PR - I ended up doing a big refactor to create Tag and TagList modules for handling tag related things so didn't directly use it - didi pick pieces tho - so appreciated
