### ISSUE TITLE
[Feature Request] Command Palette: Open Cardboard

### ISSUE THREAD

**Issue by FelipeRearden** [roovo/obsidian-card-board#6]
Hello @roovo !!!!

This is a simple FR to explain: would be amazing to have a command in the `Command Palette` to open the cardboard. 

Many Obsidian users like me hides the left icon bar to have a clean desktop window ;)
- And with a command in the command palette, we can define a hotkey to open the cardboard!

## Additional Option: Command for Specific Boards

If possible, would be amazing to have an command in the command palette for each one of the boards that we have !

`CardBoard: Open Cardboard:Title_name_1` 

Thanks for reading this FR.

I wish you a fantastic Sunday!

**Comment by roovo** [comment]
Have a basic version of this ready.  It won't let you specify which board but it opens the cardboard window.

I'll re-open this Issue when it auto-closes as it would be good to add this too.

**Comment by FelipeRearden** [comment]
> Have a basic version of this ready. It won't let you specify which board but it opens the cardboard window.

Thank you very much @roovo !!!!!
- Now I can hide my left i in bar again !!!!!!!! YES !!!!

Working perfect on version Obsidian `0.12.19` !!!

> I'll re-open this Issue when it auto-closes as it would be good to add this too.

Great @roovo  ! Thanks for letting me know 😃 !!!


Have a great day!

**Comment by roovo** [comment]
I'll aim get the ability to specify a board  done in the next main release as it should be pretty straightforward!

**Comment by FelipeRearden** [comment]
> I'll aim get the ability to specify a board  done in the next main release as it should be pretty straightforward!

Thank you very much @roovo !!!!! Great news to start the week :)


Have a great day!

**Comment by roovo** [comment]
The last part of this (being able to choose a specific board using the command palette) is now implemented and will be in the next (beta - as not on the official list yet) release :)

**Comment by FelipeRearden** [comment]
> The last part of this (being able to choose a specific board using the command palette) is now implemented and will be in the next (beta - as not on the official list yet) release :)

Thank you very much @roovo ! I will test this feature when the new public beta will be available !!!!

Have a great day!

**Comment by roovo** [comment]
You should be able to get the latest version via BRAT as I pushed the new release earlier this afternoon.  Any issues or further suggestions, just let me know.

Thank you

**Comment by FelipeRearden** [comment]
> You should be able to get the latest version (0.2.0) via BRAT as I pushed the new release earlier this afternoon.  Any issues or further suggestions, just let me know.
> 
> 
> 
> Thank you

Working on version `0.2.0` on Obsidian `0.12.19`

Thank you for this feature!
