### ISSUE TITLE
[Feature Request] Implement click on tags just like Obsidian

### ISSUE THREAD

**Issue by darthmachina** [roovo/obsidian-card-board#60]
In Obsidian, tags are clickable and clicking on one open up the search pane with the tag as the search term. It would be nice to implement the same feature in CardBoard.

Functionally it should work exactly like Obsidian: open the search pane with the clicked tag being the search term: `tag:#foo`.

**Comment by roovo** [comment]
This has been implemented in version [0.6.6(https://github.com/roovo/obsidian-card-board/releases/tag/0.6.6).
