### ISSUE TITLE
[Feature Request]  Filter by Header

### ISSUE THREAD

**Issue by ackstorm23** [roovo/obsidian-card-board#68]
I want to filter tasks by a parent header.   

I don't want to have to put a tag my tasks to ensure they will end up in a list. 

Perhaps this can be done already and I simply don't understand how to take advantage of it?

**Comment by roovo** [comment]
Parking this in #42 as this would require tracking headers whilst parsing for tasks which I currently don't do and am not sure I want to add as it will complicate the parser quite a bit.

Note that you can put tags in the page front matter if you want to apply the same tag to all tasks in a single document - see the [Readme](https://github.com/roovo/obsidian-card-board#front-matter-tags), but I presume the need here is for something more granular.

**Comment by roovo** [comment]
(also duplicate of #86)
