### ISSUE TITLE
[Bug] Link to Block gets removed when Task (also Subtask) gets annotated with @completed

### ISSUE THREAD

**Issue by p-kocsis** [roovo/obsidian-card-board#70]
Hey!
Used in tag board mode, completed with checkbox on board

### behaviour now
Before Task completion:

- [  ] Task1 ^linktoblock

After Task completion:

- [  ] Task1 @completed(2022-01-02T17:37:34)

### expected behaviour

Before Task completion:

- [  ] Task1 

After Task completion:

- [  ] Task1 @completed(2022-01-02T17:37:34) ^linktoblock

Thanks and have a great day!

**Comment by roovo** [comment]
good spot - this is cause I am not parsing block references when I consume the task lines!  I will get this fixed in the next release!

**Comment by roovo** [comment]
fixed in [release 0.4.0](https://github.com/roovo/obsidian-card-board/releases/tag/0.4.0).

I've also minimised the general munging of the content of the task line when marking tasks as complete/incomplete so things like tags won't be moved to the end, they will stay where they were originally.

**Comment by p-kocsis** [comment]
Thank you
