### ISSUE TITLE
[Bug] Completed count setting doesn't apply to board - MacOS

### ISSUE THREAD

**Issue by AnubisSec** [roovo/obsidian-card-board#76]
When setting the "Completed Count" setting within a board, 0 will get rid of the column, but any other number doesn't change the number of completed tasks shown. See below:

![image](https://user-images.githubusercontent.com/38790814/151715728-3c048a03-1297-431c-9c8c-1f2b0934c321.png)

![image](https://user-images.githubusercontent.com/38790814/151715760-96cc5c20-fd54-46f8-98b0-d88de6a6c718.png)

**Comment by stufro** [comment]
@roovo can I have a go at this one?

**Comment by AnubisSec** [comment]
Hey @stufro, did you happen to have any luck with this? No rush, just curious :)

**Comment by stufro** [comment]
@AnubisSec yeah it looks to be an easy fix, I'll make a PR for @roovo to review.

**Comment by AnubisSec** [comment]
@roovo hey there, sorry to give this a poke, was hoping this could get a quick 2 second code review and possible merge. Would be very helpful to keep the right side of my board from looking like a novel :)

Best

**Comment by roovo** [comment]
fixed in [release 3.3](https://github.com/roovo/obsidian-card-board/releases/tag/0.3.3)... thanks for raising @AnubisSec andd for the PR @stufro
