### ISSUE TITLE
[FR] Support Dataview task fields or Tasks task field for dates

### ISSUE THREAD

**Issue by dummifiedme** [roovo/obsidian-card-board#77]
Currently, as far as I could find, the plugin supports dates of the Kanban format only. 

If there could be a support for the `📆 2022-02-02` kind of due dates and `[completion:: 2022-02-03]` kind of completion dates, it would be really great. 

It would allow for multiple ways to viewing your tasks. 
- a quick query with dataview
- a kanban view with this plugin
- if someone uses Tasks plugin, they can use a Kanban view as well  :D

I hope this will be considered :)

**Comment by Rhydderch** [comment]
yes, please, this would be great ! :)
I would love for card board to be able to parse correctly tasks in the "Tasks" plugin format.
For example, I would like to be able to create a board for all the days of the week

- unscheduled
- overdue
- Monday
- Tuesday
- Wednesday
- Thursday
- Friday
- Future
- Completed

**Comment by datavistics** [comment]
@roovo Id also like to express interest here. I imagine many/most users are using tasks in this way. Is there any quick workaround, like can I specify a regex?

**Comment by roovo** [comment]
Closing this as the ask (along with some other plugin formats) is covered in #92.

@Rhydderch - I have created a separate issue around being able to create a date board like you detailed above so I can keep the idea of this separate from supporting other plugin formats.

**Comment by roovo** [comment]
just released version [0.6.0](https://github.com/roovo/obsidian-card-board/releases/tag/0.6.0) with support for Tasks formatted Due and Completion dates

**Comment by Rhydderch** [comment]
> just released version [0.6.0](https://github.com/roovo/obsidian-card-board/releases/tag/0.6.0) with support for Tasks formatted Due and Completion dates

This is awesome. I will look at using the cardboard plugin again :) Thanks for the work you put into this.

**Comment by roovo** [comment]
....and Dataview formatted due and completion dates are now supported too (version 0.6.4)

**Comment by monotykamary** [comment]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/1130103/199285157-ecf5ad92-927f-4715-b310-af2cb125f6b6.png">

@roovo I have Dataview 0.5.47 and CardBoard 0.6.4 installed, but it seems I'm not able to use formatted completion dates.

**Comment by roovo** [comment]
Yes - you are right - I will make this clearer in the dialog !!

It felt like the most sensible thing to do so if you have dataview installed, the control for automatic completion is all in the one place - saves confusion which might arise if it is set differently in each plugin.  However I am not a heavy dataview user so this is based more on presumption than personal use-case :)

I will try and make it more obvious with some better explanation.  Thank you for the comment - really appreciated

**Comment by roovo** [comment]
@monotykamary ...forgot where this discussion was ;)

just to note that I did update the settings wording in version 0.6.5 - hopefully it's a little clearer now.  Thank you again :)
