### ISSUE TITLE
Switch to board fails when vault contains large file

### ISSUE THREAD

**Issue by nickynicolson** [roovo/obsidian-card-board#82]
I had been experimenting with including a glossary note in my vault, holding c 15K lines of definitions. It seems that if a note of this size is present, the switch to board command does not work.

Steps to reproduce:
1. Set up a new vault and enable the cardboard plugin
1. Define at least two tag boards and check that opening a specific board via the command palette (using Cardboard: Open \[board name\]) works for all boards
1. Add a large note to the vault
1. Repeat step 2, i.e. open each board via the command palette (using Cardboard: Open \[board name\]) 
    - The cardboard view is shown and the specified board is highlighted briefly, then the first defined board in the set is shown. It is possible to switch to other boards using the tabbed interface at the top of the board view screen

**Comment by nickynicolson** [comment]
Fixing #27 would provide a work-around for this bug

**Comment by roovo** [comment]
Hi - and a (very) belated thanks for this.  I have got #27 on my backlog :) Admittedly it has been there for quite a while and admittedly it is also behind getting drag and drop implemented; and that is going to be a pretty big piece of work.  But it is there so I am planning on working on this.

Getting this fixed properly isn't likely to happen any time soon tho just cause of the way that the plugin works.  I do have some general ideas on how I would like to make things more efficient so large files will have less of an impact, but this won't be moving up my priority list any time soon.  It would be an interesting issue to work on tho so I will keep it open and labelled as a bug so it stays in my consciousness :)

**Comment by roovo** [comment]
The latest release (0.7.6) adds the ability to exclude files/folders - so #27 is now closed :)

So if you have any large files you know will not contain tasks you wish to see on your boards you can now exclude them!

**Comment by roovo** [comment]
Closing this as there have been a lot of updates to the plugin internals since this was raised so any issues are likely for different reasons than they were 2 years ago!

Note that there is a more recent performance-related ticket #156.
