### ISSUE TITLE
Allow "untagged" column to be custom sorted with other columns

### ISSUE THREAD

**Issue by amurena** [roovo/obsidian-card-board#84]
The untagged column is great and extremely useful for the tag board. However, it shows as the first column, where this would actually be used less regularly than the pre-defined tag columns. 

Workflow use case: Review the untagged column weekly to assign tasks to the appropriate column to manage priority. This happening once a week, it doesn't need to be the first column seen which takes up valuable screen real estate when it isn't as urgent of a workflow column.

**Comment by benhamilton** [comment]
+1 upvote
I agree with this reasoning. Untagged as last column is more useful to me.

**Comment by roovo** [comment]
Have been pondering this.....

The plan is to firstly implement collapsible columns as per #50 so you can at least minimize the impact of the column on board space.  The actual implementation of what you are after would then come in with drag and drop, as this will be the natural way of allowing this to be done.

There are a couple of things I need to get sorted before I work on collapsible columns, but I'm hoping for that part to be done reasonably soon.  Drag and drop will take a little longer :)

**Comment by roovo** [comment]
will need to think about how to persist the column order as tag boards are a mixture of user defined and cardBoard defined columns.

**Comment by roovo** [comment]
Note to self: make sure that I track which columns are collapsed when sorting columns.  There is no tracking of this at the moment so when columns are added or removed which columns are collapsed can change.

**Comment by roovo** [comment]
A quick note to say that I've just released a new version with collapsable columns, which may help a little as you can keep the untagged column collapsed when not in use.

I will be looking at the drag and drop stuff next so should be covering this issue properly as a part of that (drag andf drop colums to re-arrange them), but in the meantime this latest release may help :)

**Comment by animalSymbolicum** [comment]
I would also consider it extremely useful to switch columns/statuses by drag&drop directly on the board (e.g between #status/backlog, #status/triaged, status/blocked, #status/doing). It might also be useful to toggle between replacing and adding tags. Adding could enable to add a "next actions" tag to a "project" tag.

**Comment by roovo** [comment]
Columns can now be re-ordered as of the latest version (0.7.5)

@animalSymbolicum - see issue #11 to track implementation of dragging/dropping cards
