### ISSUE TITLE
possible use case? 

### ISSUE THREAD

**Issue by rhaynes74** [roovo/obsidian-card-board#85]
Hi folks, is it possible to use these cards as a note-card plugin, I would like to have something that would allow me to display relatively short markdown notes that I could shuffle and reorder, merge etc.

**Comment by jedth** [comment]
I don't think this is possible with this plugin, but you can check out the obsidian kanban plugin. It might come close to what you want.

**Comment by roovo** [comment]
As @jedth has said, it is not possible at the moment with CardBoard.  In addition to looking at kanban, the [next item that the core obsidian dev team are working on ](https://trello.com/b/Psqfqp7I/obsidian-roadmap)is Canvas:

You can use the Canvas view to organize notes visually. Canvas gives you infinite space to brainstorm, diagram and lay out your ideas. With Canvas view you can create mind maps, flow charts, org charts, moodboards, family trees and more.

This sounds like it is exactly what you are asking for!
