### ISSUE TITLE
Change date of a task

### ISSUE THREAD

**Issue by TfTHacker** [roovo/obsidian-card-board#9]
I would like the ability to change a due date without having to edit the file. Perhaps in the card, click on the date and have it give me a popup for changing the date.

Having said that, being able to drag a card to another column (or have arrows for moving right or left in the cardboard view) would be useful.

**Comment by roovo** [comment]
Many thanks - I'm going to close this as a duplicate of the wider ranging #11 as this idea is captured there along with other stuff.

**Comment by roovo** [comment]
I'm going to re-open this as on reflection it may be useful to think of this separately from #11 as it could be something that it would make sense to implement ahead of #11 to break things up a bit!

**Comment by darthmachina** [comment]
FWIW I would like the ability to edit the date of a task directly as well. This would be useful on a Tag Board since dates aren't directly used by the board itself but it is still information on a card.

**Comment by roovo** [comment]
closing as the latest release (0.7.8) adds a context menu which allows the due date of a task to be set/changed/cleared from the CardBoard view
