### ISSUE TITLE
More flexible date board options

### ISSUE THREAD

**Issue by roovo** [roovo/obsidian-card-board#93]
I would love for card board to be able to parse correctly tasks in the "Tasks" plugin format.
For example, I would like to be able to create a board for all the days of the week

- unscheduled
- overdue
- Monday
- Tuesday
- Wednesday
- Thursday
- Friday
- Future
- Completed

_Originally posted by @Rhydderch in https://github.com/roovo/obsidian-card-board/issues/77#issuecomment-1048665485_

**Comment by Zebrazilla** [comment]
It would also be nice to have the possibility of the current setup, but with Overdue in it's own column that could be turned off similarly to how Undated is.

**Comment by roovo** [comment]
see https://github.com/roovo/obsidian-card-board/issues/105#issuecomment-1318541666 from @juestchaos....

Maybe in terms of time dimension, I hope to increase the corresponding column, such as the current week, the current month, and the current quarter.

**Comment by roovo** [comment]
Just a small update as implementation for this will still be a while out....

....but the work I have just been doing on how boards are set up internally has been done with the idea of supporting more flexible date boards in mind so this will be much easier to implement now :)

**Comment by wimlep** [comment]
additionally support for the scheduled date from the task plugin would be nice, this would allow for 'weekplanning'

**Comment by roovo** [comment]
Hi @wimlep -> thank you -> this is definitely under consideration - see #94 to track thoughts I have on this and for any progress as and when it happens :)

Many thanks again

**Comment by DerNamenlose** [comment]
I'd like to add my 2 cents and propose to use the Start date from the Tasks plugin to hide tasks from the board. I at least use the Start date as a kind of "don't bother me until then" marker.

**Comment by sirsleon** [comment]
> I'd like to add my 2 cents and propose to use the Start date from the Tasks plugin to hide tasks from the board. I at least use the Start date as a kind of "don't bother me until then" marker.

I'd like to sort tasks into columns based on the start date, rather than the due date. It's annoying that the tasks would only leave 'Future' once it is due soon.

**Comment by roovo** [comment]
This issue is going to be focussed purely on providing more flexibility in specifying columns for date boards using the current date implementation - so due date only.

@DerNamenlose, @sirsleon, @wimlep -> I will track progress/comments on use of other date types (such as start, scheduled etc) in #94.

**Comment by roovo** [comment]
closing this issue as the latest release (0.7.5) allows for the creation of custom date based columns using relative dates.  I've hopefully linked to other issues raised here that are not directly a part of this fucntionality!
