### ISSUE TITLE
Compatibility with date formats of Obsidian Tasks plugin

### ISSUE THREAD

**Issue by gluecode** [roovo/obsidian-card-board#96]
Obsidian tasks has the following formats:

> Due: 
> - [ ] take out the trash 📅 2021-04-09
> 
> Scheduled:
> - [ ] take out the trash ⏳ 2021-04-09
> 
> Start
> - [ ] take out the trash 🛫 2021-04-09

Since Tasks is a very popular task management plugin, it'll be convenient if Cardboard recognizes this date format and adds these tasks into the board based on these dates, instead of the current format: **@due(YYYY-MM-DD).**

**Comment by roovo** [comment]
Hiya - the next release will be able to understand Due and Completion dates in Tasks format as well as give you the option to use Tasks format completion date stamps when marking as complete, so hopefully this will help.

Scheduled and Start dates will appear on the card as a part of the title as there is no concept of either of these built into CardBoard (as of yet).

**Comment by roovo** [comment]
Hi @gluecode - I've just release [version 0.6.0](https://github.com/roovo/obsidian-card-board/releases/tag/0.6.0) which is compatible with Due and Completion dates in tasks format.  I realise that this doesn't handle either scheduled or start dates in any kind of intelligent way (they will be displayed on the card with their icons.

I have added a separate issue #94 to consider the handling of date types other than Due and Completed so I'm gonna close this issue for now as handling other dates is going to require some additional thinking and will have to come later.

However, do feel free to re-open this as/if needed.
