### ISSUE TITLE
Folder exists but can't add it to the filter

### ISSUE THREAD

**Issue by pcause** [roovo/obsidian-card-board#98]
I have a folder in my vault where I keep my templater templates.  I go to the settings for the Board and type "templates" which is the name of the folder and I see nothing in the paths list.  IU can type the full folder name and the folder and subfolders are shown.  I select them and they are all added to as paths.  If I close the dialogue and reopen they are not there.

.6.0

**Comment by roovo** [comment]
ooh - you are right, there is some wierdness happening with the filter multiselect!  Thanks I will take a look as soon as poss

**Comment by roovo** [comment]
@pcause - just released 0.6.1 which (hopefully) fixes this.   Thank you so much for spotting this and raising the issue.  DO let me know if you have further problems.

**Comment by pcause** [comment]
doesn't fix.  same problem

**Comment by roovo** [comment]
well I did fix something :)  seems to be another bug lurking !! -> darn it

**Comment by pcause** [comment]
> well I did fix something :) seems to be another bug lurking !! -> darn it

I suspect you did.  Just didn't completely fix the issue.  Thought it might be the number of paths you display is limited but even when I entered in full in the box and it accepted it, when I left settings and returned it wasn't there.

**Comment by roovo** [comment]
I am able to reproduce the disappearing so have a bit of debugging to do to see why it's happening.  I should probably work out how to move the offending logic into a module where I can add some unit tests for it as the code is hard to test where it is at the moment....  See if I can work out what is happening first tho!

**Comment by roovo** [comment]
Hi @pcause - another new version for you to try -> 0.6.2.  I think I've fixed the disappearing filter issue, so do let me know if you are still seeing it.

I wasn't too sure what you meant by the first part of the bug report:

_I have a folder in my vault where I keep my templater templates. I go to the settings for the Board and type "templates" which is the name of the folder and I see nothing in the paths list._

So this may well be an issue?? If it is, could you let me know some additional details to help me reproduce: what is the directory structure you have in your vault that is not showing up and what it is you type to not see it come up.

Many thanks again - hopefully getting closer to a full fix!

**Comment by roovo** [comment]
Thank you - I'll leave this open and have a look into the search stuff to see how I can improve it ...with a little less urgency than fixing the other stuff as I was worried that could have led to some unexpected overwriting of filter settings which would not be good!

**Comment by roovo** [comment]
Hi @pcause, I've (hopefully) improved the autocomplete/search behavior - it is working better for me in my main vault so am hoping it will be for you too!  Do let me know how you get on -> version 0.6.3.

Many thanks again!

**Comment by pcause** [comment]
It worked for me.  I was able to enter the problematic folder name and the autocomplete presented it as an option and added it to the list.

from my POV you can close this

**Comment by roovo** [comment]
Fabulous - really glad it worked!  Thank you again :)

**Comment by davebhc71** [comment]
I think this issue still exists when using the plugin on iPad Mobile. No way to enter Tags options and there is NO Auto Complete. Nothing ‘sticks’!
