### ISSUE TITLE
RTL tags are ignored by the plugin

### ISSUE THREAD

**Issue by aliamini87** [roovo/obsidian-card-board#99]
Suppose you have this task :

![image](https://user-images.githubusercontent.com/91720545/197557820-b21d7112-5c39-4742-a85f-01f6fe1a77de.png)

This is the result in the card board:

![image](https://user-images.githubusercontent.com/91720545/197558106-81986100-7b10-431a-a459-f282b3bd5d47.png)

Despite two LTR tags that are identified by the cardboard, the RTL tag (persian language) is not identified.

**Comment by roovo** [comment]
Interesting - thank you.  Not even thought about RTL languages so am not totally surprised that you have found an issue.

Will take a look :)

**Comment by roovo** [comment]
Hi @aliamini87 -> this is actually happening as Cardboard is only recognizing the characters A-Z, a-z, 0-9, _, -, / as being valid content for tags...

With that in mind, I'm going to change this from bug to enhancement as supporting both non-ascii tags and RTL are more additional features (that I would like to support) than issues with the current implementation.  With that in mind, could I ask a couple of questions on how obsidian works with RTL tags:

- I presume that obsidian itself recognises the example you gave as a tag (just checking as I want to mirror obsidian's behavior if it is correct and I can).
- is the # still on the left of the tag text in RTL markdown source (i.e: is the markdown content #rtl_tag rather than rtl_tag#)
- How do #tags/subtags work in RTL in obsidian - are they the same way around as in LTR with the root tag on the left or is it reversed?
 
Many thanks in advance - look forward to getting this working for you

**Comment by aliamini87** [comment]
Hi
1. yes. obsidian considers them as tags.
2. your second question is a little complicated. because something that appears is different from something that suggested. see the pictures below: (sorry print screen doesn't work in this situation)

![image](https://user-images.githubusercontent.com/91720545/198654741-5531130c-52b9-462d-997f-fc93986bcc89.png)

![image](https://user-images.githubusercontent.com/91720545/198655519-f28debf8-c6dc-4e36-a36f-ed07dffc1dc7.png)

As you see suggestion is different from what appeared in the text.

and this is in reading mode :

![image](https://user-images.githubusercontent.com/91720545/198656369-4d89198a-22e8-4e6a-9299-2b8a4b66fbc4.png)


3. about subtags:

![image](https://user-images.githubusercontent.com/91720545/198659003-ca1c9476-09b8-4d7f-9a60-c2770e9f38ad.png)

In reading mode:

![image](https://user-images.githubusercontent.com/91720545/198657972-271dadbb-fd92-4241-acf3-8ae16b4abf02.png)

**Comment by roovo** [comment]
interesting - and thank you so much.

If possible, could attach an example markdown file containing some example RTL tasks with  tags (including with subtags), as this will make it clearer what the source looks like.  Then I will have some examples to test my parsing against - which will hopefully get me reading the tasks properly.

For the subtag example, is:

![Screenshot 2022-10-28 at 20 58 09](https://user-images.githubusercontent.com/5251/198721831-51024bd3-4167-4c29-9875-a481a80b4d64.png)

The parent part, and 

![Screenshot 2022-10-28 at 20 58 56](https://user-images.githubusercontent.com/5251/198721941-832cce1d-5358-49f4-aeb5-9e39933a6b9d.png)

the sub part?

Thank you again

**Comment by aliamini87** [comment]
This is a simple note with both tags and subtag.
Tell me if you need something else.
[2022-10-29.md](https://github.com/roovo/obsidian-card-board/files/9893830/2022-10-29.md)

**Comment by roovo** [comment]
fabulous - thank you that's great.  Loaded into my test vault.

I'm just finishing off my "other-plugin-compatibility" work then I will get on to this as it is going to be an interesting one to tackle and it's a pretty fundamental requirement to be able to properly support other languages! (Persian looks so beautiful)

I will have more questions as I get stuck in :)

**Comment by roovo** [comment]
Hi @aliamini87, I've got the first bit of this done.  The latest release ([0.6.5](https://github.com/roovo/obsidian-card-board/releases/tag/0.6.5)) recognises RTL characters (in fact any Unicode characters) in tags, so Persian language tags (e.g. #تگ/زیرتگ) should now be picked up.

I realise that this isn't full RTL support and I would like to support better, so what else could/should I do to improve things?

My current plans are to check if RTL is selected in the obsidian editor settings and if it is:
- place the '#' on the right for tags which are in RTL script
- put the card check-boxes on the right and generally right align the card contents

Do let me know if there is anything else you feel I should try to get working.  Many thanks :)

**Comment by aliamini87** [comment]
Thank you very much.

![image](https://user-images.githubusercontent.com/91720545/204098683-48051307-0c3e-4f8b-b3f0-d74bf374eb44.png)

It's really usable now. 
If I find something, I will make an issue for that.
For now, the only minor thing that I see is that the checkboxes location in the RTL lines should be in the right.
Thanks again and good luck.

**Comment by roovo** [comment]
Thank you - I've added a new issue to track the general improvement for better RTL support: #113

**Comment by roovo** [comment]
Hiya - I've just pushed a new version [0.6.6](https://github.com/roovo/obsidian-card-board/releases/tag/0.6.6) that I hope supports the obsidian RTL setting in a sensible way.  If you use this setting and could have a look and see how it looks/works that would be great.

Any feedback/suggestions would be gratefully received!

![Screenshot 2022-11-27 at 21 18 58](https://user-images.githubusercontent.com/5251/204160199-a2e0fc81-5558-47f3-bfe9-e764ebf2858a.png)

**Comment by aliamini87** [comment]
It's  amazing. Thanks a lot.
